sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -f Dockerfile.dev -t ambraspace/docker-react .

script:
  - docker run -e CI=true ambraspace/docker-react npm run test
